"""
tests/integration/test_local_supabase_stack.py

Stage 5A.3 evidence: proves the local Supabase stack's Auth, Data API
(PostgREST), Storage, and Edge Functions all actually work end-to-end,
not just that their containers are running.

Requires:
    - Docker + `supabase start` already running
    - `supabase status -o env > .env.supabase.local` already run
    - python -m pip install -r requirements-maintainer.txt

Run with:
    python -m pytest -m integration -v

These tests never touch the real cloud pilot project. All test data is
prefixed to be unmistakably disposable and is cleaned up after each test.
"""

import time
import uuid

import pytest
from stack_support import cleanup_storage, connect_local_database, require_status

# pytest imports this module during collection even when the integration
# marker is deselected, so these must not be hard imports: an analyst clone
# with only requirements-dev.txt installed would fail `pytest -q` outright.
psycopg2 = pytest.importorskip(
    "psycopg2",
    reason="integration lane needs: python -m pip install -r requirements-maintainer.txt",
)

pytestmark = pytest.mark.integration


# ---------------------------------------------------------------------
# Data API (PostgREST)
# ---------------------------------------------------------------------


def test_data_api_insert_and_select(local_stack, local_http):
    """Create a disposable table via direct DB connection, then prove the
    Data API (PostgREST) can insert/select against it over HTTP."""
    table_name = f"zz_migration_smoke_{uuid.uuid4().hex[:8]}"

    conn = connect_local_database(psycopg2.connect, local_stack["db_url"])
    conn.autocommit = True
    cur = conn.cursor()
    try:
        cur.execute(
            f"""
            create table public.{table_name} (
                id bigint generated by default as identity primary key,
                note text not null
            );
            """
        )
        # PostgREST only exposes tables to roles with grants; local dev
        # stack's anon/authenticated roles need explicit access here.
        cur.execute(f"grant select, insert on public.{table_name} to anon;")
        cur.execute(f"grant usage, select on sequence public.{table_name}_id_seq to anon;")
        cur.execute(f"alter table public.{table_name} enable row level security;")
        cur.execute(
            f"""create policy "allow_all_smoke_test" on public.{table_name}
                for all using (true) with check (true);"""
        )

        # PostgREST caches the schema and doesn't notice new tables created
        # via a raw SQL connection until told to reload. Without this, the
        # very next request returns a 404 "not in schema cache" error even
        # though the table genuinely exists.
        cur.execute("notify pgrst, 'reload schema';")
        time.sleep(0.5)  # reload is asynchronous; give PostgREST a moment

        headers = {
            "apikey": local_stack["publishable_key"],
            "Authorization": f"Bearer {local_stack['publishable_key']}",
            "Content-Type": "application/json",
            "Prefer": "return=representation",
        }

        insert_resp = local_http.post(
            f"{local_stack['rest_url']}/{table_name}",
            json={"note": "5a3-smoke-test"},
            headers=headers,
            timeout=10,
        )
        require_status(insert_resp, (201,), "Data API insert")
        inserted = insert_resp.json()[0]
        assert inserted["note"] == "5a3-smoke-test"

        select_resp = local_http.get(
            f"{local_stack['rest_url']}/{table_name}",
            headers=headers,
            timeout=10,
        )
        require_status(select_resp, (200,), "Data API select")
        rows = select_resp.json()
        assert any(r["note"] == "5a3-smoke-test" for r in rows)
    finally:
        cur.execute(f"drop table if exists public.{table_name} cascade;")
        cur.close()
        conn.close()


# ---------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------


def test_auth_signup_and_cleanup(local_stack, local_http):
    """Prove local GoTrue (Auth) accepts a signup, then clean the user up
    via the admin API so no disposable accounts pile up in the local
    stack across repeated test runs."""
    test_email = f"algoguard.test+{uuid.uuid4().hex[:8]}@algoguard.invalid"
    test_password = "SmokeTest!" + uuid.uuid4().hex[:8]

    signup_resp = local_http.post(
        f"{local_stack['api_url']}/auth/v1/signup",
        json={"email": test_email, "password": test_password},
        headers={
            "apikey": local_stack["publishable_key"],
            "Content-Type": "application/json",
        },
        timeout=10,
    )
    require_status(signup_resp, (200, 201), "Auth signup")
    body = signup_resp.json()
    user_id = (body.get("user") or body).get("id")
    assert user_id, "No user id in signup response."

    # Cleanup: delete the disposable user via the admin endpoint.
    delete_resp = local_http.delete(
        f"{local_stack['api_url']}/auth/v1/admin/users/{user_id}",
        headers={
            "apikey": local_stack["secret_key"],
            "Authorization": f"Bearer {local_stack['secret_key']}",
        },
        timeout=10,
    )
    require_status(delete_resp, (200, 204), "Auth cleanup")


# ---------------------------------------------------------------------
# Storage
# ---------------------------------------------------------------------


def test_storage_upload_download_cleanup(local_stack, local_http):
    """Create a disposable private bucket, upload a small object, confirm
    the bytes round-trip correctly, then remove both."""
    bucket_name = f"zz-smoke-{uuid.uuid4().hex[:8]}"
    object_path = "smoke.txt"
    content = b"5a3-storage-smoke-test"

    admin_headers = {
        "apikey": local_stack["secret_key"],
        "Authorization": f"Bearer {local_stack['secret_key']}",
        "Content-Type": "application/json",
    }

    create_bucket_resp = local_http.post(
        f"{local_stack['api_url']}/storage/v1/bucket",
        json={"name": bucket_name, "public": False},
        headers=admin_headers,
        timeout=10,
    )
    require_status(create_bucket_resp, (200, 201), "Storage bucket creation")

    try:
        upload_resp = local_http.post(
            f"{local_stack['api_url']}/storage/v1/object/{bucket_name}/{object_path}",
            data=content,
            headers={
                "apikey": local_stack["secret_key"],
                "Authorization": f"Bearer {local_stack['secret_key']}",
                "Content-Type": "text/plain",
            },
            timeout=10,
        )
        require_status(upload_resp, (200, 201), "Storage upload")

        download_resp = local_http.get(
            f"{local_stack['api_url']}/storage/v1/object/{bucket_name}/{object_path}",
            headers={
                "apikey": local_stack["secret_key"],
                "Authorization": f"Bearer {local_stack['secret_key']}",
            },
            timeout=10,
        )
        require_status(download_resp, (200,), "Storage download")
        assert download_resp.content == content
    finally:
        cleanup_storage(local_http, local_stack["api_url"], bucket_name, object_path, admin_headers)


# ---------------------------------------------------------------------
# Edge Functions
# ---------------------------------------------------------------------


def test_edge_function_smoke(local_stack, local_http):
    """Invoke the disposable smoke_test Edge Function
    (supabase/functions/smoke_test) and confirm it responds. Requires
    `supabase start` to have picked up the function from the repo's
    supabase/functions directory."""
    resp = local_http.post(
        f"{local_stack['functions_url']}/smoke_test",
        headers={
            "apikey": local_stack["publishable_key"],
            "Authorization": f"Bearer {local_stack['publishable_key']}",
        },
        timeout=10,
    )
    require_status(resp, (200,), "Edge Function invocation")
    body = resp.json()
    assert body.get("message") == "ok"
