"""
tests/integration/test_local_supabase_stack.py

Stage 5A.3 evidence: proves the local Supabase stack's Auth, Data API
(PostgREST), Storage, and Edge Functions all actually work end-to-end,
not just that their containers are running.

Requires:
    - Docker + `supabase start` already running
    - `supabase status -o env > .env.supabase.local` already run
    - pip install requests psycopg2-binary

Run with:
    pytest -m integration -v

These tests never touch the real cloud pilot project. All test data is
prefixed to be unmistakably disposable and is cleaned up after each test.
"""
import time
import uuid

import psycopg2
import pytest
import requests

pytestmark = pytest.mark.integration


# ---------------------------------------------------------------------
# Data API (PostgREST)
# ---------------------------------------------------------------------

def test_data_api_insert_and_select(local_stack):
    """Create a disposable table via direct DB connection, then prove the
    Data API (PostgREST) can insert/select against it over HTTP."""
    table_name = f"zz_migration_smoke_{uuid.uuid4().hex[:8]}"

    conn = psycopg2.connect(local_stack["db_url"], sslmode="prefer")
    conn.autocommit = True
    cur = conn.cursor()
    try:
        cur.execute(
            f"""
            create table public.{table_name} (
                id bigint generated by default as identity primary key,
                note text not null
            );
            """
        )
        # PostgREST only exposes tables to roles with grants; local dev
        # stack's anon/authenticated roles need explicit access here.
        cur.execute(f"grant select, insert on public.{table_name} to anon;")
        cur.execute(f"grant usage, select on sequence public.{table_name}_id_seq to anon;")
        cur.execute(f"alter table public.{table_name} enable row level security;")
        cur.execute(
            f"""create policy "allow_all_smoke_test" on public.{table_name}
                for all using (true) with check (true);"""
        )

        # PostgREST caches the schema and doesn't notice new tables created
        # via a raw SQL connection until told to reload. Without this, the
        # very next request returns a 404 "not in schema cache" error even
        # though the table genuinely exists.
        cur.execute("notify pgrst, 'reload schema';")
        time.sleep(0.5)  # reload is asynchronous; give PostgREST a moment

        headers = {
            "apikey": local_stack["publishable_key"],
            "Authorization": f"Bearer {local_stack['publishable_key']}",
            "Content-Type": "application/json",
            "Prefer": "return=representation",
        }

        insert_resp = requests.post(
            f"{local_stack['rest_url']}/{table_name}",
            json={"note": "5a3-smoke-test"},
            headers=headers,
            timeout=10,
        )
        assert insert_resp.status_code == 201, insert_resp.text
        inserted = insert_resp.json()[0]
        assert inserted["note"] == "5a3-smoke-test"

        select_resp = requests.get(
            f"{local_stack['rest_url']}/{table_name}",
            headers=headers,
            timeout=10,
        )
        assert select_resp.status_code == 200, select_resp.text
        rows = select_resp.json()
        assert any(r["note"] == "5a3-smoke-test" for r in rows)
    finally:
        cur.execute(f"drop table if exists public.{table_name} cascade;")
        cur.close()
        conn.close()


# ---------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------

def test_auth_signup_and_cleanup(local_stack):
    """Prove local GoTrue (Auth) accepts a signup, then clean the user up
    via the admin API so no disposable accounts pile up in the local
    stack across repeated test runs."""
    test_email = f"algoguard.test+{uuid.uuid4().hex[:8]}@algoguard.invalid"
    test_password = "SmokeTest!" + uuid.uuid4().hex[:8]

    signup_resp = requests.post(
        f"{local_stack['api_url']}/auth/v1/signup",
        json={"email": test_email, "password": test_password},
        headers={
            "apikey": local_stack["publishable_key"],
            "Content-Type": "application/json",
        },
        timeout=10,
    )
    assert signup_resp.status_code in (200, 201), signup_resp.text
    body = signup_resp.json()
    user_id = (body.get("user") or body).get("id")
    assert user_id, f"No user id in signup response: {body}"

    # Cleanup: delete the disposable user via the admin endpoint.
    delete_resp = requests.delete(
        f"{local_stack['api_url']}/auth/v1/admin/users/{user_id}",
        headers={
            "apikey": local_stack["secret_key"],
            "Authorization": f"Bearer {local_stack['secret_key']}",
        },
        timeout=10,
    )
    assert delete_resp.status_code in (200, 204), delete_resp.text


# ---------------------------------------------------------------------
# Storage
# ---------------------------------------------------------------------

def test_storage_upload_download_cleanup(local_stack):
    """Create a disposable private bucket, upload a small object, confirm
    the bytes round-trip correctly, then remove both."""
    bucket_name = f"zz-smoke-{uuid.uuid4().hex[:8]}"
    object_path = "smoke.txt"
    content = b"5a3-storage-smoke-test"

    admin_headers = {
        "apikey": local_stack["secret_key"],
        "Authorization": f"Bearer {local_stack['secret_key']}",
        "Content-Type": "application/json",
    }

    create_bucket_resp = requests.post(
        f"{local_stack['api_url']}/storage/v1/bucket",
        json={"name": bucket_name, "public": False},
        headers=admin_headers,
        timeout=10,
    )
    assert create_bucket_resp.status_code in (200, 201), create_bucket_resp.text

    try:
        upload_resp = requests.post(
            f"{local_stack['api_url']}/storage/v1/object/{bucket_name}/{object_path}",
            data=content,
            headers={
                "apikey": local_stack["secret_key"],
                "Authorization": f"Bearer {local_stack['secret_key']}",
                "Content-Type": "text/plain",
            },
            timeout=10,
        )
        assert upload_resp.status_code in (200, 201), upload_resp.text

        download_resp = requests.get(
            f"{local_stack['api_url']}/storage/v1/object/{bucket_name}/{object_path}",
            headers={
                "apikey": local_stack["secret_key"],
                "Authorization": f"Bearer {local_stack['secret_key']}",
            },
            timeout=10,
        )
        assert download_resp.status_code == 200
        assert download_resp.content == content
    finally:
        requests.delete(
            f"{local_stack['api_url']}/storage/v1/object/{bucket_name}/{object_path}",
            headers=admin_headers,
            timeout=10,
        )
        requests.delete(
            f"{local_stack['api_url']}/storage/v1/bucket/{bucket_name}",
            headers=admin_headers,
            timeout=10,
        )


# ---------------------------------------------------------------------
# Edge Functions
# ---------------------------------------------------------------------

def test_edge_function_smoke(local_stack):
    """Invoke the disposable smoke_test Edge Function
    (supabase/functions/smoke_test) and confirm it responds. Requires
    `supabase start` to have picked up the function from the repo's
    supabase/functions directory."""
    resp = requests.post(
        f"{local_stack['functions_url']}/smoke_test",
        headers={
            "apikey": local_stack["publishable_key"],
            "Authorization": f"Bearer {local_stack['publishable_key']}",
        },
        timeout=10,
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body.get("message") == "ok"
