-- Stage 5B.1 — identity core: profiles, protected roles, nodes, memberships.
--
-- Nothing here is reachable yet: RLS is enabled with no policies, and
-- 20260922010000 removed the API roles' table privileges. 5B.4 adds the
-- policies; 5B.3 adds the enrollment/administration Edge Function.
--
-- State columns are `text` with a CHECK rather than an enum. Enum values
-- cannot be removed, and ALTER TYPE ... ADD VALUE has transaction caveats
-- that fight the one-file-one-transaction rule. A CHECK constraint is
-- edited by an ordinary migration that rolls back cleanly.

-- ---------------------------------------------------------------------
-- profile — cloud identity + historical attribution
-- ---------------------------------------------------------------------
create table public.profile (
    profile_id        bigint generated by default as identity primary key,

    -- Optional: legacy rows imported in 5E have attribution but no cloud
    -- login until someone enrols. GENERATED BY DEFAULT (not ALWAYS) so the
    -- import can carry legacy identifiers across explicitly.
    auth_user_id      uuid unique references auth.users (id) on delete restrict,

    -- SQLite admin.admin_id. Kept so imported traffic/predictions/reports
    -- still point at a person after the port.
    legacy_admin_id   bigint unique,

    -- SQLite admin.username. A display name in the cloud: login is by
    -- email through Auth, and usernames are not credentials any more.
    username          text not null unique,
    email             text,
    is_active         boolean not null default true,

    created_at        timestamptz not null default now(),
    legacy_created_at text,

    constraint profile_has_an_identity
        check (auth_user_id is not null or legacy_admin_id is not null)
);

-- Deliberate: no password_hash column. Auth owns credentials. Copying
-- SQLite's admin.password_hash into the cloud would create a second,
-- unmanaged credential store with none of Auth's rotation or lockout.
comment on table public.profile is
    'Cloud identity and legacy attribution. Contains no credentials: Auth owns those.';
comment on column public.profile.auth_user_id is
    'auth.users.id. ON DELETE RESTRICT: deleting a login must not silently orphan evidence.';

create index profile_auth_user_id_idx on public.profile (auth_user_id);

-- ---------------------------------------------------------------------
-- user_role — the protected current-role record
-- ---------------------------------------------------------------------
-- Authorization reads THIS table, never a JWT claim. A token minted before
-- an Administrator was demoted stays valid until it expires; if the token
-- decided permissions, so would the stale role. Token metadata may mirror
-- roles for display only (plan, Part II).
create table public.user_role (
    profile_id bigint not null references public.profile (profile_id) on delete cascade,
    role       text not null check (role in ('administrator', 'analyst')),
    granted_at timestamptz not null default now(),
    granted_by bigint references public.profile (profile_id),

    primary key (profile_id, role)
);

comment on table public.user_role is
    'Current protected roles. Authorization checks read here; JWT role claims are display only.';

create index user_role_role_idx on public.user_role (role);

-- ---------------------------------------------------------------------
-- node — one AlgoGuard installation
-- ---------------------------------------------------------------------
-- node_id is generated by the installation and is a CLAIM, not proof.
-- Approval binds it to people; a hostile client editing its UUID gets a
-- pending node with no memberships, which authorizes nothing.
create table public.node (
    node_id        uuid primary key,
    display_name   text not null,
    status         text not null default 'pending'
                   check (status in ('pending', 'approved', 'rejected', 'revoked')),

    first_seen_at  timestamptz not null default now(),
    last_seen_at   timestamptz,
    approved_at    timestamptz,
    approved_by    bigint references public.profile (profile_id),
    decision_note  text,

    -- Reported by the installation for humans to recognise it in the
    -- approval queue. Never an authorization input: hostname and IP are
    -- attacker-controlled (plan, 5B.3).
    hostname_hint  text,

    constraint node_approval_is_recorded
        check (status <> 'approved' or (approved_at is not null and approved_by is not null))
);

comment on column public.node.node_id is
    'Installation-generated UUID. A claim, not an attestation: approval is what grants anything.';
comment on column public.node.hostname_hint is
    'Display only. Hostname/IP never grant access.';

create index node_status_idx on public.node (status);

-- ---------------------------------------------------------------------
-- node_membership — Administrator-approved user-to-node binding
-- ---------------------------------------------------------------------
create table public.node_membership (
    membership_id bigint generated by default as identity primary key,
    node_id       uuid   not null references public.node (node_id) on delete restrict,
    profile_id    bigint not null references public.profile (profile_id) on delete restrict,

    status        text not null default 'pending'
                  check (status in ('pending', 'approved', 'revoked')),

    -- One approved membership per person is their local node; the rest are
    -- explicit (plan: "One user may have multiple explicit memberships").
    is_default    boolean not null default false,

    requested_at  timestamptz not null default now(),
    decided_at    timestamptz,
    decided_by    bigint references public.profile (profile_id),
    decision_note text,

    -- Re-running enrollment must not queue a second request for the same
    -- pair ("Repeated startup/enrollment does not duplicate a node").
    constraint node_membership_unique_pair unique (node_id, profile_id),

    constraint node_membership_decision_is_recorded
        check (status = 'pending' or (decided_at is not null and decided_by is not null)),

    -- A revoked or pending membership is not somebody's default node.
    constraint node_membership_default_is_approved
        check (not is_default or status = 'approved')
);

create unique index node_membership_one_default_per_profile
    on public.node_membership (profile_id)
    where is_default;

create index node_membership_profile_status_idx
    on public.node_membership (profile_id, status);
create index node_membership_node_status_idx
    on public.node_membership (node_id, status);

comment on table public.node_membership is
    'Administrator-approved binding of a profile to a node. Authorizes submission for that node only.';

-- ---------------------------------------------------------------------
-- Deny by default
-- ---------------------------------------------------------------------
-- RLS on + zero policies = no rows for anon or authenticated, and the
-- REVOKEs mean they cannot reach the tables at all. Both layers on
-- purpose: a privilege slip alone should not be enough to read evidence.
alter table public.profile         enable row level security;
alter table public.user_role       enable row level security;
alter table public.node            enable row level security;
alter table public.node_membership enable row level security;

revoke all on table public.profile         from anon, authenticated;
revoke all on table public.user_role       from anon, authenticated;
revoke all on table public.node            from anon, authenticated;
revoke all on table public.node_membership from anon, authenticated;
