-- Stage 5B.1 — the ported application tables.
--
-- Port rules applied throughout:
--
--  * Primary keys and counters are BIGINT. SQLite INTEGER is 64-bit; a
--    Postgres `integer` would silently narrow the range at import.
--  * Identity columns are GENERATED BY DEFAULT, never ALWAYS, so 5E's
--    import can carry the original row identifiers across and preserve
--    every existing relationship without OVERRIDING SYSTEM VALUE.
--  * Legacy timestamps keep their original names, their `text` type and
--    their canonical UTC text. Converting them here would make the import
--    a lossy reformat; 6B can add a derived timestamptz column with the
--    parse rules written down. New lifecycle columns use timestamptz.
--  * Legacy 0/1 flags stay integer, with a CHECK, for the same reason.
--  * JSON-bearing columns stay `text`. jsonb would reject any legacy row
--    that is not valid JSON, turning a data-fidelity problem into a failed
--    import at cutover.
--  * Every node-scoped table carries node_id and a UNIQUE (pk, node_id).
--    Child rows then reference the PAIR, so a direct API write cannot
--    attach this node's prediction to another node's traffic — the
--    constraint refuses it even if a policy is wrong (plan, 5B.4).

-- ---------------------------------------------------------------------
-- training_run — maintainer-side, not node-scoped
-- ---------------------------------------------------------------------
create table public.training_run (
    run_id                  bigint generated by default as identity primary key,
    created_by              bigint references public.profile (profile_id) on delete restrict,

    filename                text not null,
    stored_filename         text,
    upload_timestamp        text not null,
    row_count               bigint,
    feature_count           bigint,
    normal_count            bigint,
    anomaly_count           bigint,
    target_column           text,
    class_distribution      text,
    validation_status       text not null default 'pending',
    preprocessing_status    text not null default 'pending',
    training_status         text not null default 'pending',
    recommended_model_id    bigint,
    recommended_model_name  text,
    recommended_score       double precision,
    deployment_status       text not null default 'not_deployed',
    completed_at            text,
    error_message           text
);

comment on table public.training_run is
    'Training is maintainer-only (plan, 6D.1). No node_id: runs are global, not an installation''s evidence.';

create index training_run_uploaded_idx on public.training_run (upload_timestamp desc);

-- ---------------------------------------------------------------------
-- detection_model
-- ---------------------------------------------------------------------
create table public.detection_model (
    model_id              bigint generated by default as identity primary key,
    run_id                bigint references public.training_run (run_id) on delete restrict,

    model_name            text not null,
    model_type            text,
    version               text,
    training_date         text,

    accuracy              double precision,
    precision_score       double precision,
    recall                double precision,
    f1_score              double precision,
    specificity           double precision,
    fpr                   double precision,
    roc_auc               double precision,
    cpu_usage             double precision,
    ram_usage             double precision,
    training_time         double precision,
    model_size            double precision,

    evaluation_status     text not null default 'completed',
    error_message         text,

    normalized_accuracy   double precision,
    normalized_precision  double precision,
    normalized_recall     double precision,
    normalized_f1         double precision,
    normalized_roc_auc    double precision,
    normalized_fpr        double precision,
    normalized_cpu        double precision,
    normalized_ram        double precision,
    normalized_model_size double precision,
    overall_score         double precision,
    rank                  integer,

    artifact_path         text,
    is_recommended        integer not null default 0 check (is_recommended in (0, 1)),
    is_deployed           integer not null default 0 check (is_deployed in (0, 1)),
    deployed_at           text
);

create index detection_model_run_idx on public.detection_model (run_id, rank);

-- ---------------------------------------------------------------------
-- model_deployment
-- ---------------------------------------------------------------------
create table public.model_deployment (
    deployment_id           bigint generated by default as identity primary key,
    model_id                bigint not null references public.detection_model (model_id) on delete restrict,
    run_id                  bigint not null references public.training_run (run_id) on delete restrict,
    deployed_by             bigint references public.profile (profile_id) on delete restrict,

    artifact_path           text not null,
    deployed_at             text not null,
    is_active               integer not null default 1 check (is_active in (0, 1)),
    replaced_deployment_id  bigint references public.model_deployment (deployment_id)
);

-- "Publishers preserve one active model" (plan, 5C acceptance) as a
-- database constraint, not an application convention: two concurrent
-- activations cannot both win.
create unique index model_deployment_single_active
    on public.model_deployment (is_active)
    where is_active = 1;

create index model_deployment_active_idx
    on public.model_deployment (is_active, deployed_at desc);

-- ---------------------------------------------------------------------
-- capture_session — node-scoped
-- ---------------------------------------------------------------------
create table public.capture_session (
    capture_id        bigint generated by default as identity primary key,
    node_id           uuid   not null references public.node (node_id) on delete restrict,
    owner_profile_id  bigint not null references public.profile (profile_id) on delete restrict,

    interface         text,
    bpf_filter        text,
    started_at        text not null,
    finished_at       text,
    packets_captured  bigint not null default 0,
    packets_dropped   bigint not null default 0,
    flows_emitted     bigint not null default 0,
    status            text not null default 'running',

    -- New lifecycle times: timestamptz, unlike the ported text columns.
    opened_at         timestamptz not null default now(),
    closed_at         timestamptz,

    constraint capture_session_scope unique (capture_id, node_id)
);

create index capture_session_node_idx on public.capture_session (node_id, opened_at desc);

-- ---------------------------------------------------------------------
-- network_traffic — node-scoped
-- ---------------------------------------------------------------------
create table public.network_traffic (
    traffic_id        bigint generated by default as identity primary key,
    node_id           uuid   not null references public.node (node_id) on delete restrict,
    owner_profile_id  bigint not null references public.profile (profile_id) on delete restrict,
    capture_id        bigint,

    "timestamp"       text not null,
    source_ip         text,
    destination_ip    text,
    source_port       integer,
    destination_port  integer,
    protocol          text,
    packet_size       bigint,
    flags             text,
    dataset_source    text,
    feature_payload   text,

    recorded_at       timestamptz not null default now(),

    constraint network_traffic_scope unique (traffic_id, node_id),
    constraint network_traffic_capture_same_node
        foreign key (capture_id, node_id)
        references public.capture_session (capture_id, node_id) on delete restrict
);

create index network_traffic_node_time_idx on public.network_traffic (node_id, recorded_at desc);
create index network_traffic_capture_idx on public.network_traffic (capture_id);

-- ---------------------------------------------------------------------
-- prediction — node-scoped
-- ---------------------------------------------------------------------
create table public.prediction (
    prediction_id         bigint generated by default as identity primary key,
    node_id               uuid   not null references public.node (node_id) on delete restrict,
    owner_profile_id      bigint not null references public.profile (profile_id) on delete restrict,

    traffic_id            bigint not null,
    model_id              bigint not null references public.detection_model (model_id) on delete restrict,
    deployment_id         bigint references public.model_deployment (deployment_id) on delete restrict,

    model_name            text,
    predicted_label       text not null,
    confidence_score      double precision,
    prediction_timestamp  text not null,
    latency_ms            double precision,
    alert_created         integer not null default 0 check (alert_created in (0, 1)),
    input_payload         text,

    created_at            timestamptz not null default now(),

    constraint prediction_scope unique (prediction_id, node_id),
    constraint prediction_traffic_same_node
        foreign key (traffic_id, node_id)
        references public.network_traffic (traffic_id, node_id) on delete restrict
);

create index prediction_node_time_idx on public.prediction (node_id, created_at desc);
create index prediction_timestamp_idx on public.prediction (prediction_timestamp desc);
create index prediction_traffic_idx on public.prediction (traffic_id);

-- ---------------------------------------------------------------------
-- alert — node-scoped
-- ---------------------------------------------------------------------
create table public.alert (
    alert_id        bigint generated by default as identity primary key,
    node_id         uuid   not null references public.node (node_id) on delete restrict,
    owner_profile_id bigint not null references public.profile (profile_id) on delete restrict,

    prediction_id   bigint not null,

    -- Legacy label, preserved as-is. 6A.3 adds attack_probability and a
    -- versioned band alongside it; old values are never re-interpreted
    -- into the new scale (plan: "Unknown old scores remain unavailable,
    -- not fabricated").
    severity_level  text not null,
    alert_status    text not null,
    detected_at     text not null,
    description     text,

    created_at      timestamptz not null default now(),

    constraint alert_scope unique (alert_id, node_id),
    constraint alert_prediction_same_node
        foreign key (prediction_id, node_id)
        references public.prediction (prediction_id, node_id) on delete restrict
);

create index alert_node_detected_idx on public.alert (node_id, detected_at desc);
create index alert_detected_idx on public.alert (detected_at desc);
create index alert_prediction_idx on public.alert (prediction_id);

-- ---------------------------------------------------------------------
-- report / report_alert
-- ---------------------------------------------------------------------
-- node_id is nullable here alone: an Administrator's cross-node report has
-- no single node. A NULL node means "not an analyst's report", and 5B.4
-- restricts those rows to Administrators. Because a composite FK with a
-- NULL column is satisfied vacuously, cross-node membership of a report is
-- a policy decision, not a constraint one — stated here so the gap is not
-- discovered later.
create table public.report (
    report_id         bigint generated by default as identity primary key,
    node_id           uuid references public.node (node_id) on delete restrict,
    owner_profile_id  bigint not null references public.profile (profile_id) on delete restrict,
    run_id            bigint references public.training_run (run_id) on delete restrict,

    report_type       text not null,
    date_range_start  text,
    date_range_end    text,
    generated_at      text not null,

    created_at        timestamptz not null default now(),

    constraint report_scope unique (report_id, node_id)
);

create index report_node_idx on public.report (node_id, created_at desc);
create index report_owner_idx on public.report (owner_profile_id);

create table public.report_alert (
    report_id bigint not null,
    alert_id  bigint not null,
    node_id   uuid,

    primary key (report_id, alert_id),

    constraint report_alert_report_same_node
        foreign key (report_id, node_id)
        references public.report (report_id, node_id) on delete restrict,
    constraint report_alert_alert_same_node
        foreign key (alert_id, node_id)
        references public.alert (alert_id, node_id) on delete restrict
);

create index report_alert_alert_idx on public.report_alert (alert_id);

-- ---------------------------------------------------------------------
-- system_log
-- ---------------------------------------------------------------------
-- node_id is nullable: maintainer-side actions (training, publication,
-- account administration) have no node. 5B.4 restricts NULL-node log rows
-- to Administrators.
create table public.system_log (
    log_id            bigint generated by default as identity primary key,
    node_id           uuid references public.node (node_id) on delete restrict,
    profile_id        bigint references public.profile (profile_id) on delete restrict,

    module            text not null,
    action            text not null,
    status            text not null,
    message           text,
    run_id            bigint references public.training_run (run_id) on delete restrict,
    dataset_filename  text,
    model_name        text,
    prediction_id     bigint,
    ip_address        text,
    "timestamp"       text not null,

    created_at        timestamptz not null default now(),

    constraint system_log_scope unique (log_id, node_id),
    constraint system_log_prediction_same_node
        foreign key (prediction_id, node_id)
        references public.prediction (prediction_id, node_id) on delete restrict
);

create index system_log_node_time_idx on public.system_log (node_id, created_at desc);
create index system_log_run_idx on public.system_log (run_id, "timestamp" desc);
create index system_log_timestamp_idx on public.system_log ("timestamp" desc);

-- ---------------------------------------------------------------------
-- Deny by default
-- ---------------------------------------------------------------------
alter table public.training_run     enable row level security;
alter table public.detection_model  enable row level security;
alter table public.model_deployment enable row level security;
alter table public.capture_session  enable row level security;
alter table public.network_traffic  enable row level security;
alter table public.prediction       enable row level security;
alter table public.alert            enable row level security;
alter table public.report           enable row level security;
alter table public.report_alert     enable row level security;
alter table public.system_log       enable row level security;

revoke all on table public.training_run     from anon, authenticated;
revoke all on table public.detection_model  from anon, authenticated;
revoke all on table public.model_deployment from anon, authenticated;
revoke all on table public.capture_session  from anon, authenticated;
revoke all on table public.network_traffic  from anon, authenticated;
revoke all on table public.prediction       from anon, authenticated;
revoke all on table public.alert            from anon, authenticated;
revoke all on table public.report           from anon, authenticated;
revoke all on table public.report_alert     from anon, authenticated;
revoke all on table public.system_log       from anon, authenticated;
