-- Stage 5B.1 — structures later stages depend on: event deduplication
-- (5D's outbox) and model manifests (5C's publication/delivery).
--
-- The behaviour lands in those stages. The tables land now, in the stage
-- that owns schema and permissions, so nothing has to add a table to a
-- live pilot later and re-argue its policies.

-- ---------------------------------------------------------------------
-- ingest_event — one immutable row per event the outbox ever submits
-- ---------------------------------------------------------------------
-- The outbox retries whenever an acknowledgement is lost, so the same
-- event arrives more than once and the database, not the client, has to
-- decide it is the same event. The UUID is the identity; content_sha256
-- is what makes a *different* payload under a reused UUID detectable
-- rather than silently accepted (plan, 5B.5).
create table public.ingest_event (
    event_uuid        uuid primary key,
    node_id           uuid   not null references public.node (node_id) on delete restrict,
    owner_profile_id  bigint not null references public.profile (profile_id) on delete restrict,

    capture_id        bigint,
    deployment_id     bigint references public.model_deployment (deployment_id) on delete restrict,

    -- When the event happened on the node, not when the cloud saw it.
    -- Both are kept: queue age is the difference.
    event_time        timestamptz not null,
    received_at       timestamptz not null default now(),

    content_sha256    char(64) not null check (content_sha256 ~ '^[0-9a-f]{64}$'),

    -- Filled by the 5B.5 transaction that writes the flow group. NULL
    -- means "accepted but not yet materialised" only inside that
    -- transaction; a committed row has its references.
    traffic_id        bigint,
    prediction_id     bigint,
    alert_id          bigint,

    constraint ingest_event_scope unique (event_uuid, node_id),

    constraint ingest_event_capture_same_node
        foreign key (capture_id, node_id)
        references public.capture_session (capture_id, node_id) on delete restrict,
    constraint ingest_event_traffic_same_node
        foreign key (traffic_id, node_id)
        references public.network_traffic (traffic_id, node_id) on delete restrict,
    constraint ingest_event_prediction_same_node
        foreign key (prediction_id, node_id)
        references public.prediction (prediction_id, node_id) on delete restrict,
    constraint ingest_event_alert_same_node
        foreign key (alert_id, node_id)
        references public.alert (alert_id, node_id) on delete restrict,

    -- An alert without its prediction, or a prediction without its
    -- traffic, is a partial flow group. 5B.5 writes them atomically; this
    -- refuses the shape outright.
    constraint ingest_event_flow_group_is_whole
        check (
            (alert_id is null or prediction_id is not null)
            and (prediction_id is null or traffic_id is not null)
        )
);

create index ingest_event_node_time_idx on public.ingest_event (node_id, event_time desc);
create index ingest_event_owner_idx on public.ingest_event (owner_profile_id);

comment on table public.ingest_event is
    'Deduplication anchor for outbox submissions. Same UUID + same content = already accepted; same UUID + different content = rejected.';

-- ---------------------------------------------------------------------
-- model_manifest — what a client verifies before it deserialises anything
-- ---------------------------------------------------------------------
create table public.model_manifest (
    manifest_id             bigint generated by default as identity primary key,
    deployment_id           bigint not null references public.model_deployment (deployment_id) on delete restrict,
    model_id                bigint not null references public.detection_model (model_id) on delete restrict,

    -- Path inside the private `models` bucket. UNIQUE and never rewritten:
    -- publication uploads a new object, it does not overwrite an old one.
    object_path             text not null unique,
    object_sha256           char(64) not null check (object_sha256 ~ '^[0-9a-f]{64}$'),
    object_bytes            bigint not null check (object_bytes > 0),

    -- Compatibility gate. A client that does not match refuses the
    -- artifact BEFORE unpickling it — joblib.load on an artifact built by
    -- a different scikit-learn is exactly the step that must not run on
    -- unverified input.
    workflow_version        text not null,
    feature_schema_version  text not null,
    python_version          text not null,
    dependency_versions     text not null,

    status                  text not null default 'draft'
                            check (status in ('draft', 'published', 'active', 'superseded', 'orphaned')),

    created_at              timestamptz not null default now(),
    created_by              bigint references public.profile (profile_id) on delete restrict,
    activated_at            timestamptz,
    superseded_at           timestamptz,
    note                    text,

    constraint model_manifest_activation_is_recorded
        check (status <> 'active' or activated_at is not null)
);

-- At most one active manifest, enforced by the database. Upload and
-- commit are separate operations; a failed activation leaves an
-- 'orphaned' row for cleanup and the previous active manifest untouched.
create unique index model_manifest_single_active
    on public.model_manifest (status)
    where status = 'active';

create index model_manifest_deployment_idx on public.model_manifest (deployment_id);

-- ---------------------------------------------------------------------
-- deployment_activation_lock — the permanent singleton row
-- ---------------------------------------------------------------------
-- 5C serialises activation by locking this row (SELECT ... FOR UPDATE)
-- before touching manifest status. A row lock, not an advisory lock:
-- advisory locks are session-scoped and this path runs through a
-- transaction pooler, where a session is not a stable thing to hold.
create table public.deployment_activation_lock (
    lock_id    boolean primary key default true check (lock_id),
    locked_at  timestamptz not null default now()
);

insert into public.deployment_activation_lock (lock_id) values (true)
on conflict (lock_id) do nothing;

comment on table public.deployment_activation_lock is
    'Exactly one row, forever. SELECT ... FOR UPDATE on it serialises model activation (5C.2).';

-- ---------------------------------------------------------------------
-- Deny by default
-- ---------------------------------------------------------------------
alter table public.ingest_event               enable row level security;
alter table public.model_manifest             enable row level security;
alter table public.deployment_activation_lock enable row level security;

revoke all on table public.ingest_event               from anon, authenticated;
revoke all on table public.model_manifest             from anon, authenticated;
revoke all on table public.deployment_activation_lock from anon, authenticated;
